### ISSUE TITLE
Use containers/image library for docker-less pull and mount

### ISSUE THREAD

**Issue by aweiteka** [openshift/image-inspector#35]
Requiring access to the docker.socket is a lot of privilege. With the https://github.com/containers/image/ library this should not be required.

**Comment by simon3z** [comment]
@aweiteka that's great! When we started in 2015 there wasn't anything like that yet!

Replacing the docker socket connection with this would be a great step forward. We would still need the secrets to be used to access to the restricted registries but that's OK.

cc @enoodle @pweil-

**Comment by enoodle** [comment]
I was poking around and it looks good and will be easy to use (I wish there was a real documentation instead of "look we have skopeo using it", but its a new project), I think I can make a PR for this if we want. 

That being said, we will have a backward compatibility problem with applications that need the old local docker digest:
This library will only give us access to the RepoDigest of images, but for the use case of ManageIQ with image-inspector with old docker daemon we will need the local digest to verify that the image that we scanned is the image that we intended to scan.

**Comment by simon3z** [comment]
> This library will only give us access to the RepoDigest of images, but for the use case of ManageIQ with image-inspector with old docker daemon we will need the local digest to verify that the image that we scanned is the image that we intended to scan.

@enoodle if we release a new version we can break this API. Do we really need the local digest nowadays for any reason? (Or just backward-compatibility?)
