### ISSUE TITLE
Logging to disk or stderr appears broken when scanning running containers

### ISSUE THREAD

**Issue by rhdedgar** [openshift/image-inspector#84]
For example. running something like:
image-inspector -scan-type=clamav -clam-socket=/host/run/clamd.scan/clamd.sock -container=5ca8650f8245 -alsologtostderr -log_dir=/var/log/clam/

only returns this. with none of the actual scan results.:
2017/12/08 23:47:55 clamav scan took 117s (1 problems found)

I tried several variations of this, with a combination of every parameter and verbosity level I could find supported by image-inspector, and it seems only -post-results-url works as expected for me. I have been sending the results with -post-results-url successfully to a different tool that the catches the results, but it image-inspector doesn't log directly to disk or stderr when including that parameter, either.

Can anyone confirm logfile / stderror logging works when scanning running containers? Or provide an example in the event this could still be user error?

Thanks!

**Comment by simon3z** [comment]
@enoodle can you check this? Any suggestion for @rhdedgar ?
I think @legionus and @mfojtik were mostly involved in this part, any insight?

**Comment by enoodle** [comment]
@rhdedgar I am not sure what else it should print. As far as I can see this is the only log print from the clam scanner, and afterwords image-inspector should post the results or serve them. Image-Inspector is not printing the scan report to the logs.

In the case of clamv no report is generated, and we apparently don't serve the raw results.
@simon3z @rhdedgar Do you want me to add an endpoint for the result so that when run with `--serve=0.0.0.0:8080` (for example) it will be possible to get the results from the `/api/v1/results` endpoint? It seems like we already have everything for that and it was forgotten somewhere when implementing the imageserver`
